mode: deployment

image:
  repository: otel/opentelemetry-collector-contrib
  tag: 0.69.0

config:
  processors:
    k8sattributes: {}
  exporters:
    logging: {}
    otlp/honeycomb:
      endpoint: api.honeycomb.io:443
      headers:
        "x-honeycomb-team": "nRIzsDPQqVYJT7XM2CliLA"
    jaeger:
      endpoint: jaegertron2-collector:14250
      tls:
        insecure: true
  service:
    extensions: [health_check]
    pipelines:
      traces:
        receivers: [otlp]
        processors: [memory_limiter, batch, k8sattributes]
        exporters: [otlp/honeycomb, logging, jaeger]
      metrics:
      logs:

# disable ports that are not required
ports:
  jaeger-binary:
    enabled: false
  jaeger-compact:
    enabled: false
  jaeger-thrift:
    enabled: false
  jaeger-grpc:
    enabled: false
  jaeger-http:
    enabled: false
  zipkin:
    enabled: false

serviceAccount:
  create: true

resources:
  limits:
    cpu: 500m
    memory: 2Gi
  requests:
    cpu: 200m
    memory: 400Mi
